/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\3262704574\\Desktop\\blogs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3a64b367",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a64b367").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2e3567e7",
    path: "/blogs/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e3567e7").then(next)
    },
  },
  {
    name: "v-fed7c2f2",
    path: "/blogs/2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fed7c2f2").then(next)
    },
  },
  {
    name: "v-5a1a55b2",
    path: "/blogs/3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a1a55b2").then(next)
    },
  },
  {
    name: "v-77b04267",
    path: "/blogs/5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77b04267").then(next)
    },
  },
  {
    name: "v-25518bc7",
    path: "/blogs/4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25518bc7").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-add31ff8",
    path: "/tag/html-css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-add31ff8").then(next)
    },
    meta: {"pid":"tags","id":"html-css"}
  },
  {
    path: "/tag/html-css/index.html",
    redirect: "/tag/html-css/"
  },
  {
    name: "v-2aa50a6a",
    path: "/tag/查看/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2aa50a6a").then(next)
    },
    meta: {"pid":"tags","id":"查看"}
  },
  {
    path: "/tag/查看/index.html",
    redirect: "/tag/查看/"
  },
  {
    name: "v-7a5f6990",
    path: "/tag/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7a5f6990").then(next)
    },
    meta: {"pid":"tags","id":"JavaScript"}
  },
  {
    path: "/tag/JavaScript/index.html",
    redirect: "/tag/JavaScript/"
  },
  {
    name: "v-66172787",
    path: "/tag/jQuery/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-66172787").then(next)
    },
    meta: {"pid":"tags","id":"jQuery"}
  },
  {
    path: "/tag/jQuery/index.html",
    redirect: "/tag/jQuery/"
  },
  {
    name: "v-6dbf3fe0",
    path: "/categories/html-css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6dbf3fe0").then(next)
    },
    meta: {"pid":"categories","id":"html-css"}
  },
  {
    path: "/categories/html-css/index.html",
    redirect: "/categories/html-css/"
  },
  {
    name: "v-081e6844",
    path: "/categories/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-081e6844").then(next)
    },
    meta: {"pid":"categories","id":"JavaScript"}
  },
  {
    path: "/categories/JavaScript/index.html",
    redirect: "/categories/JavaScript/"
  },
  {
    name: "v-73b5aa93",
    path: "/categories/jQuery/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-73b5aa93").then(next)
    },
    meta: {"pid":"categories","id":"jQuery"}
  },
  {
    path: "/categories/jQuery/index.html",
    redirect: "/categories/jQuery/"
  },
  {
    name: "v-60bcb791",
    path: "/categories/Ajax/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-60bcb791").then(next)
    },
    meta: {"pid":"categories","id":"Ajax"}
  },
  {
    path: "/categories/Ajax/index.html",
    redirect: "/categories/Ajax/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]