/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "jxz的博客",
  "description": "(精通JavaScript,vue(2,3),jQuery,uni-app,html,css...)",
  "base": "/blogs1/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/aa.jpg",
        "heroText": "jiangxiz",
        "bgImageStyle": {
          "height": "100%",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        },
        "heroImageStyle": {
          "maxHeight": "288px",
          "display": "block",
          "borderRadius": "19% 81% 23% 77% / 44% 57% 43% 56%",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3a64b367",
      "path": "/"
    },
    {
      "title": "html-css",
      "frontmatter": {
        "title": "html-css",
        "date": "2023-1-1",
        "categories": [
          "html-css"
        ],
        "tags": [
          "html-css",
          "查看"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-2e3567e7",
      "path": "/blogs/1.html",
      "headers": [
        {
          "level": 3,
          "title": "样式格式介绍",
          "slug": "样式格式介绍"
        },
        {
          "level": 3,
          "title": "html中基础标签",
          "slug": "html中基础标签"
        }
      ]
    },
    {
      "title": "JavaScript",
      "frontmatter": {
        "title": "JavaScript",
        "date": "2023-1-1",
        "categories": [
          "JavaScript"
        ],
        "tags": [
          "JavaScript",
          "查看"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-fed7c2f2",
      "path": "/blogs/2.html"
    },
    {
      "title": "jQuery",
      "frontmatter": {
        "title": "jQuery",
        "date": "2023-1-1",
        "categories": [
          "jQuery"
        ],
        "tags": [
          "jQuery",
          "查看"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/3.html",
      "relativePath": "blogs/3.md",
      "key": "v-5a1a55b2",
      "path": "/blogs/3.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/blogs/5.html",
      "relativePath": "blogs/5.md",
      "key": "v-77b04267",
      "path": "/blogs/5.html"
    },
    {
      "title": "Ajax",
      "frontmatter": {
        "title": "Ajax",
        "date": "2023-1-1",
        "categories": [
          "Ajax"
        ],
        "tags": [
          "JavaScript",
          "查看"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/4.html",
      "relativePath": "blogs/4.md",
      "key": "v-25518bc7",
      "path": "/blogs/4.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "html-css Tags"
      },
      "regularPath": "/tag/html-css/",
      "key": "v-add31ff8",
      "path": "/tag/html-css/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "查看 Tags"
      },
      "regularPath": "/tag/%E6%9F%A5%E7%9C%8B/",
      "key": "v-2aa50a6a",
      "path": "/tag/查看/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JavaScript Tags"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "jQuery Tags"
      },
      "regularPath": "/tag/jQuery/",
      "key": "v-66172787",
      "path": "/tag/jQuery/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "html-css Categories"
      },
      "regularPath": "/categories/html-css/",
      "key": "v-6dbf3fe0",
      "path": "/categories/html-css/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "JavaScript Categories"
      },
      "regularPath": "/categories/JavaScript/",
      "key": "v-081e6844",
      "path": "/categories/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "jQuery Categories"
      },
      "regularPath": "/categories/jQuery/",
      "key": "v-73b5aa93",
      "path": "/categories/jQuery/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Ajax Categories"
      },
      "regularPath": "/categories/Ajax/",
      "key": "v-60bcb791",
      "path": "/categories/Ajax/"
    }
  ],
  "themeConfig": {
    "logo": "/aa.jpg",
    "authorAvatar": "/aa.jpg",
    "type": "blog",
    "author": "Shuai ge",
    "nav": [],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "博客"
      },
      "tag": {
        "location": 4,
        "text": "Tag"
      }
    },
    "locales": {
      "/": {
        "lang": "zh-CN"
      }
    }
  }
}