/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "html-css": {
      "key": "html-css",
      "scope": "tags",
      "path": "/tag/html-css/",
      "pageKeys": [
        "v-2e3567e7"
      ]
    },
    "查看": {
      "key": "查看",
      "scope": "tags",
      "path": "/tag/查看/",
      "pageKeys": [
        "v-2e3567e7",
        "v-fed7c2f2",
        "v-5a1a55b2",
        "v-25518bc7"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-fed7c2f2",
        "v-25518bc7"
      ]
    },
    "jQuery": {
      "key": "jQuery",
      "scope": "tags",
      "path": "/tag/jQuery/",
      "pageKeys": [
        "v-5a1a55b2"
      ]
    }
  },
  "categories": {
    "html-css": {
      "key": "html-css",
      "scope": "categories",
      "path": "/categories/html-css/",
      "pageKeys": [
        "v-2e3567e7"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-fed7c2f2"
      ]
    },
    "jQuery": {
      "key": "jQuery",
      "scope": "categories",
      "path": "/categories/jQuery/",
      "pageKeys": [
        "v-5a1a55b2"
      ]
    },
    "Ajax": {
      "key": "Ajax",
      "scope": "categories",
      "path": "/categories/Ajax/",
      "pageKeys": [
        "v-25518bc7"
      ]
    }
  },
  "timeline": {}
}