/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-7170897d",
        "v-78617fc6"
      ]
    },
    "手写": {
      "key": "手写",
      "scope": "tags",
      "path": "/tag/手写/",
      "pageKeys": [
        "v-7170897d",
        "v-78617fc6"
      ]
    }
  },
  "categories": {
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-7170897d"
      ]
    },
    "刷题": {
      "key": "刷题",
      "scope": "categories",
      "path": "/categories/刷题/",
      "pageKeys": [
        "v-78617fc6"
      ]
    }
  },
  "timeline": {}
}