/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "html-css",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/html-css/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "查看",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/查看/","interval":[0,4]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "JavaScript",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/JavaScript/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "jQuery",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/jQuery/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "html-css",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/html-css/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "JavaScript",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/JavaScript/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "jQuery",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/jQuery/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "Ajax",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/Ajax/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]